### ISSUE TITLE
App crashes upon opening image

### ISSUE THREAD

**Issue by domdomegg** [nicolas-raoul/apps-android-commons#106]
```
USER_COMMENT=
ANDROID_VERSION=6.0
APP_VERSION_NAME=1.12
BRAND=Android
PHONE_MODEL=Android SDK built for x86_64
CUSTOM_DATA=
STACK_TRACE=android.content.res.Resources$NotFoundException: String resource ID #0x0
	at android.content.res.Resources.getText(Resources.java:312)
	at android.content.res.Resources.getString(Resources.java:400)
	at fr.free.nrw.commons.LicenseList.nameForTemplate(LicenseList.java:71)
	at fr.free.nrw.commons.LicenseList.<init>(LicenseList.java:26)
	at fr.free.nrw.commons.media.MediaDetailFragment.onCreateView(MediaDetailFragment.java:115)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1478)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:927)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1460)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:472)
	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1068)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:914)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1436)
	at android.view.View.measure(View.java:18788)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
	at android.view.View.measure(View.java:18788)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:18788)
	at android.view.ViewGroup.measureChildWithMargins(Vi
```

May be related to #103, although the error message is substantially different. I think I know [why this happens though](https://github.com/nicolas-raoul/apps-android-commons/blob/master/commons/src/main/java/fr/free/nrw/commons/LicenseList.java#L71).

**Comment by domdomegg** [comment]
Fixed in #107
