### ISSUE TITLE
Uploading from SD card does not work with API 23+ permissions

### ISSUE THREAD

**Issue by domdomegg** [nicolas-raoul/apps-android-commons#117]
Can't seem to replicate it on the emulator, only my actual phone.

App crashes if you try to upload a file by selecting the gallery option and then choose an image that is saved on the SD card. I don't know why it doesn't occur with emulator as I have tested simulating a SD card on it.

Also thinking about it this should also apply to ACCESS_FINE_LOCATION too

Need to implement this:
https://developer.android.com/training/permissions/requesting.html

```
ANDROID_VERSION=6.0.1
APP_VERSION_NAME=1.13
BRAND=samsung
PHONE_MODEL=SM-G920F
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to resume activity {fr.free.nrw.commons/fr.free.nrw.commons.upload.ShareActivity}: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=962, uid=10319 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4155)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4245)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3360)
at android.app.ActivityThread.access$1100(ActivityThread.java:221)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7224)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=962, uid=10319 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
at android.os.Parcel.readException(Parcel.java:1620)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
at android.content.ContentResolver.query(ContentResolver.java:502)
at android.content.ContentResolver.query(ContentResolver.java:445)
at fr.free.nrw.commons.upload.FileUtils.getDataColumn(FileUtils.java:103)
at fr.free.nrw.commons.upload.FileUtils.getPath(FileUtils.java:68)
at fr.free.nrw.commons.upload.ShareActivity.onResume(ShareActivity.java:214)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1286)
at android.app.Activity.performResume(Activity.java:6987)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4144)
... 10 more
java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=962, uid=10319 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
at android.os.Parcel.readException(Parcel.java:1620)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
at android.content.ContentResolver.query(ContentResolver.java:502)
at android.content.ContentResolver.query(ContentResolver.java:445)
at fr.free.nrw.commons.upload.FileUtils.getDataColumn(FileUtils.java:103)
at fr.free.nrw.commons.upload.FileUtils.getPath(FileUtils.java:68)
at fr.free.nrw.commons.upload.ShareActivity.onResume(ShareActivity.java:214)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1286)
at android.app.Activity.performResume(Activity.java:6987)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4144)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4245)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3360)
at android.app.ActivityThread.access$1100(ActivityThread.java:221)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7224)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by misaochan** [comment]
Wow, good catch. I have not been able to test the app on a real phone with API 23+, since I'm running a Samsung Galaxy S4 (heh).

**Comment by domdomegg** [comment]
I am busy at the moment (will probably get round to this on Friday - maybe?), but this is a pretty serious bug so I wouldn't advise updating the app on the Google Play Store yet, wait for this bugfix to be released

**Comment by misaochan** [comment]
Sure, no worries.

**Comment by domdomegg** [comment]
My branch [temp-fix-permissions-117](https://github.com/domdomegg/apps-android-commons/tree/temp-fix-permissions-117) is a very temporary solution, which is to make the app compiled with API 22 so that it treats it as an old app so for now it doesn't crash.

Don't create a pull request, this is just if you want to test other stuff while a proper fix comes.

**Comment by misaochan** [comment]
Great! Could you submit a pull request for fix-permissions-117 please?

**Comment by domdomegg** [comment]
It's only got a solution for READ_EXTERNAL_STORAGE, the main thing was I know how to actually implement permissions. It will still crash frequently when it requests location permissions, but I will get round to doing them soon.

I'll create a pull request once all the permissions are fixed :)

**Comment by domdomegg** [comment]
See PR #121

**Comment by misaochan** [comment]
Fixed by @domdomegg
