### ISSUE TITLE
SSLPeerUnverifiedException: No peer certificate in PrefixUpdater.java

### ISSUE THREAD

**Issue by misaochan** [nicolas-raoul/apps-android-commons#133]
By Ramnarayan.K 	

User comment:
Have had 3 failures in 14 uploads or attempts to upload,  usually when it is searching for tags

```
USER_COMMENT=Searching for tags while uploading an image 
ANDROID_VERSION=4.4.4
APP_VERSION_NAME=1.12
BRAND=Xiaomi
PHONE_MODEL=2014818
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.RuntimeException: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
at fr.free.nrw.commons.category.PrefixUpdater.doInBackground(PrefixUpdater.java:66)
at fr.free.nrw.commons.category.CategorizationFragment$4.doInBackground(CategorizationFragment.java:366)
at fr.free.nrw.commons.category.CategorizationFragment$4.doInBackground(CategorizationFragment.java:361)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more
Caused by: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
at com.android.org.conscrypt.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:146)
at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:93)
at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:388)
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:165)
at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
at in.yuvi.http.fluent.Http$HttpRequestBuilder.asResponse(Http.java:470)
at org.mediawiki.api.ApiResult.fromRequestBuilder(ApiResult.java:44)
at org.mediawiki.api.MWApi.makeRequest(MWApi.java:186)
at org.mediawiki.api.MWApi.access$000(MWApi.java:30)
at org.mediawiki.api.MWApi$RequestBuilder.get(MWApi.java:46)
at fr.free.nrw.commons.category.PrefixUpdater.doInBackground(PrefixUpdater.java:63)
... 7 more
java.lang.RuntimeException: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
at fr.free.nrw.commons.category.PrefixUpdater.doInBackground(PrefixUpdater.java:66)
at fr.free.nrw.commons.category.CategorizationFragment$4.doInBackground(CategorizationFragment.java:366)
at fr.free.nrw.commons.category.CategorizationFragment$4.doInBackground(CategorizationFragment.java:361)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
at com.android.org.conscrypt.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:146)
at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:93)
at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:388)
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:165)
at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
at in.yuvi.http.fluent.Http$HttpRequestBuilder.asResponse(Http.java:470)
at org.mediawiki.api.ApiResult.fromRequestBuilder(ApiResult.java:44)
at org.mediawiki.api.MWApi.makeRequest(MWApi.java:186)
at org.mediawiki.api.MWApi.access$000(MWApi.java:30)
at org.mediawiki.api.MWApi$RequestBuilder.get(MWApi.java:46)
at fr.free.nrw.commons.category.PrefixUpdater.doInBackground(PrefixUpdater.java:63)
... 7 more
javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
at com.android.org.conscrypt.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:146)
at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:93)
at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:388)
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:165)
at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
at in.yuvi.http.fluent.Http$HttpRequestBuilder.asResponse(Http.java:470)
at org.mediawiki.api.ApiResult.fromRequestBuilder(ApiResult.java:44)
at org.mediawiki.api.MWApi.makeRequest(MWApi.java:186)
at org.mediawiki.api.MWApi.access$000(MWApi.java:30)
at org.mediawiki.api.MWApi$RequestBuilder.get(MWApi.java:46)
at fr.free.nrw.commons.category.PrefixUpdater.doInBackground(PrefixUpdater.java:63)
at fr.free.nrw.commons.category.CategorizationFragment$4.doInBackground(CategorizationFragment.java:366)
at fr.free.nrw.commons.category.CategorizationFragment$4.doInBackground(CategorizationFragment.java:361)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
```

**Comment by misaochan** [comment]
From what I've read, it seems the only option to solve this issue on client-side is http://stackoverflow.com/questions/17159657/javax-net-ssl-sslpeerunverifiedexception-no-peer-certificate . However AFAIK using the fix in that thread will compromise security.

Otherwise, apparently the problem lies on server-side? Should we try to contact WMF about this?

**Comment by misaochan** [comment]
Hm, maybe I could just patch this by returning an empty array list if this exception is caught. I mean, in that case the user just doesn't get any category suggestions, which isn't great but might be better than crashing?

**Comment by nicolas-raoul** [comment]
Apparently this could lead to session hijacking, so better avoid it...

While waiting for any potential fix, returning an empty array as you
suggest could work, but I guess the exact same problem will happen when
trying to upload the picture, right?
Good thing is that we have the email address of a user who has this
problem, so we can have them test the fix. We could also ask them for their
list of certificates, if that makes sense.

How about posting a clear question about this on StackOverflow, stressing
that it is for use over the public Internet to a single hard-coded server
URL. Specify the Android version and the target URL, stressing that this
URL has a proper certificate. Ask why the error appears and what is
recommended in such a case. Post the URL here so that we can upvote the
question :-)

**Comment by misaochan** [comment]
The upload starts before CategorizationFragment is called though, which is where the user was at when the app crashed. So since he got that far (to PrefixUpdater) I assume he didn't crash when uploading?

Okay, will ask on StackOverflow.

**Comment by misaochan** [comment]
http://stackoverflow.com/questions/38217746/sslpeerunverifiedexception-no-peer-certificate

**Comment by nicolas-raoul** [comment]
Hum, the code section is very specific to the app... would you mind putting the lowest-level (Java HTTP level) code instead?
And also write the real URL, if people want to check what certificate that URL uses.

**Comment by misaochan** [comment]
That code isn't in the app, right? How do I find the relevant parts?

Modified to include URL
