### ISSUE TITLE
SecurityException: Permission Denial: opening x that is not exported from uid 10071

### ISSUE THREAD

**Issue by misaochan** [nicolas-raoul/apps-android-commons#135]
Sent by andrea as on 28 Mar:

```
USER_COMMENT=stavo guardando le immagini inserite
ANDROID_VERSION=N
APP_VERSION_NAME=1.6
BRAND=google
PHONE_MODEL=Nexus 6
CUSTOM_DATA=
STACK_TRACE=java.lang.SecurityException: Permission Denial: opening provider com.google.android.apps.photos.contentprovider.MediaContentProvider from ProcessRecord{74546b4 2401:fr.free.nrw.commons/u0a165} (pid=2401, uid=10165) that is not exported from uid 10071
at android.os.Parcel.readException(Parcel.java:1666)
at android.os.Parcel.readException(Parcel.java:1619)
at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:4035)
at android.app.ActivityThread.acquireProvider(ActivityThread.java:5210)
at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2210)
at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1485)
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1101)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:954)
at android.content.ContentResolver.openInputStream(ContentResolver.java:674)
at fr.free.nrw.commons.upload.UploadService.uploadContribution(UploadService.java:176)
at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:114)
at fr.free.nrw.commons.upload.UploadService.handle(UploadService.java:27)
at fr.free.nrw.commons.HandlerService$ServiceHandler.handleMessage(HandlerService.java:19)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by misaochan** [comment]
Fixing this using the answer found at http://stackoverflow.com/questions/21082708/java-lang-securityexception-permission-denial-opening-provider-com-google-andr
