### ISSUE TITLE
IllegalArgumentException: filename cannot be null

### ISSUE THREAD

**Issue by misaochan** [nicolas-raoul/apps-android-commons#152]
Posted by Krzyzstof on 3 Jul:

```
USER_COMMENT=Tried to upload a png 
ANDROID_VERSION=5.0.1
APP_VERSION_NAME=1.15
BRAND=Huawei
PHONE_MODEL=ALE-L21
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.free.nrw.commons/fr.free.nrw.commons.upload.ShareActivity}: java.lang.IllegalArgumentException: filename cannot be null
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2406)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
at android.app.ActivityThread.access$1200(ActivityThread.java:152)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5538)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.IllegalArgumentException: filename cannot be null
at android.media.ExifInterface.&lt;init&gt;(ExifInterface.java:125)
at fr.free.nrw.commons.upload.GPSExtractor.getCoords(GPSExtractor.java:85)
at fr.free.nrw.commons.upload.ShareActivity.getLocationData(ShareActivity.java:333)
at fr.free.nrw.commons.upload.ShareActivity.onCreate(ShareActivity.java:277)
at android.app.Activity.performCreate(Activity.java:6013)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)
... 10 more
java.lang.IllegalArgumentException: filename cannot be null
at android.media.ExifInterface.&lt;init&gt;(ExifInterface.java:125)
at fr.free.nrw.commons.upload.GPSExtractor.getCoords(GPSExtractor.java:85)
at fr.free.nrw.commons.upload.ShareActivity.getLocationData(ShareActivity.java:333)
at fr.free.nrw.commons.upload.ShareActivity.onCreate(ShareActivity.java:277)
at android.app.Activity.performCreate(Activity.java:6013)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
at android.app.ActivityThread.access$1200(ActivityThread.java:152)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5538)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)


```

**Comment by mujahid-sagoon** [comment]
Any update on this?
facing the same issue.

**Comment by nicolas-raoul** [comment]
@mujahid-sagoon What version of the app are you using? You can see in "About".
Thanks for the feedback! :-)

**Comment by mujahid-sagoon** [comment]
Thanks for the quick response @nicolas-raoul 
The issue is coming on Android 7.0 , device Samsug Galaxy J7.

**Comment by nicolas-raoul** [comment]
@mujahid-sagoon What version of the app are you using? Please send a screenshot of the app's left menu.

**Comment by nicolas-raoul** [comment]
@mujahid-sagoon Have you ever tried this application? https://play.google.com/store/apps/details?id=fr.free.nrw.commons
If not, then you are at the wrong place, and should ask your question at stackoverflow.com
Cheers!
