### ISSUE TITLE
Crash on startup when launching in CM 13 (Marshmallow)

### ISSUE THREAD

**Issue by dbrant** [nicolas-raoul/apps-android-commons#45]
Stack trace:

java.lang.RuntimeException: Unable to create application fr.free.nrw.commons.CommonsApplication: java.lang.NullPointerException: Attempt to get length of null array
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4759)
 at android.app.ActivityThread.-wrap1(ActivityThread.java)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:148)
 at android.app.ActivityThread.main(ActivityThread.java:5466)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
 at com.nostra13.universalimageloader.cache.disc.LimitedDiscCache.calculateCacheSizeAndFillUsageMap(LimitedDiscCache.java:73)
 at com.nostra13.universalimageloader.cache.disc.LimitedDiscCache.<init>(LimitedDiscCache.java:67)
 at com.nostra13.universalimageloader.cache.disc.impl.TotalSizeLimitedDiscCache.<init>(TotalSizeLimitedDiscCache.java:56)
 at com.nostra13.universalimageloader.cache.disc.impl.TotalSizeLimitedDiscCache.<init>(TotalSizeLimitedDiscCache.java:45)
 at fr.free.nrw.commons.CommonsApplication.onCreate(CommonsApplication.java:109)
 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4756)
 at android.app.ActivityThread.-wrap1(ActivityThread.java) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424) 
 at android.os.Handler.dispatchMessage(Handler.java:102) 
 at android.os.Looper.loop(Looper.java:148) 
 at android.app.ActivityThread.main(ActivityThread.java:5466) 
 at java.lang.reflect.Method.invoke(Native Method) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by misaochan** [comment]
Hi @dbrant ,

Thanks for reporting this. Is the problem reproducible? Does it happen all the time when you launch the app, or only occasionally?

**Comment by dbrant** [comment]
Yep, it happens every time (with a clean install of the app).

**Comment by dbrant** [comment]
Fixed, as of the last update!
