### ISSUE TITLE
NullPointerException at MwVolleyApi$Query.toString

### ISSUE THREAD

**Issue by nicolas-raoul** [nicolas-raoul/apps-android-commons#56]
@misaochan is it related to the new code?

```
USER_COMMENT=when uploading a photo application has been crashed .why this problem ? i unistall and reinstall app but problems not solve ?please fix it.
ANDROID_VERSION=5.1.1
APP_VERSION_NAME=1.8
BRAND=samsung
PHONE_MODEL=SM-J200G
CUSTOM_DATA=
STACK_TRACE=java.lang.NullPointerException: Attempt to get length of null array
at fr.free.nrw.commons.upload.MwVolleyApi$Query.toString(MwVolleyApi.java:199)
at fr.free.nrw.commons.upload.MwVolleyApi$QueryResponse.toString(MwVolleyApi.java:186)
at fr.free.nrw.commons.upload.MwVolleyApi$LogResponseListener.onResponse(MwVolleyApi.java:112)
at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65)
at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6946)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by misaochan** [comment]
@nicolas-raoul I can't seem to reproduce this, but I'll implement a null check for that array.

**Comment by misaochan** [comment]
Is this still a problem after the null check, can we close it?

**Comment by nicolas-raoul** [comment]
I am not the original reporter for this one, so I am not sure how to reproduce it, but let's close it yes!
